doctrine:
  orm:
    mappings:
      Shared:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Shared/Domain'
        prefix: App\Shared\Domain
        alias: Shared
      Depense:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Depense/Domain'
        prefix: App\Depense\Domain
        alias: Depense
      Parametrage:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Parametrage/Entity'
        prefix: App\Parametrage\Entity
        alias: Parametrage
